apiVersion: v1
kind: Secret
metadata:
  name: webbanhang-secrets
type: Opaque
stringData:
  sa_password: "Cson22102005@"
  minio_access_key: "minioadmin"
  minio_secret_key: "Cson22102005@"
  minio_public_endpoint: "192.168.49.2:31295"